### ISSUE TITLE
'Start a private network' tutorial fails if using secret phrase for --suri

### ISSUE THREAD

**Issue by gslancaster** [substrate-developer-hub/substrate-docs#831] opened 2022-02-11 15:42 UTC
### What browsers are you seeing the problem on?

Chrome

### Bug report for the website

In the tutorial on https://docs.substrate.io/tutorials/v3/private-network/ it says about the node-template `--suri` parameter:

'Replace <your-secret-seed> with the secret phrase or secret seed'

However, if the secret phrase is used to insert keys into the key store then, after the nodes are restarted, they will fail during startup with messages like this:

```
2022-02-11 13:41:01 GRANDPA voter error: Signing("Failed to sign GRANDPA vote for round 1 targetting 0x28bbc9db6478de5454464ac1f7cafe5d31e29dc36a52807344ad0f4da0be8d70")    
2022-02-11 13:41:01 Essential task `grandpa-voter` failed. Shutting down service.    
Error: Service(Other("Essential task failed."))
```

Using the secret seed for `--suri`, however, works as expected.

### Steps to reproduce the problem

1. Follow the tutorial at https://docs.substrate.io/tutorials/v3/private-network/  until reaching step 3 of the 'Add keys to the keystore' section ('Insert the aura secret key...')
2. For this step, use the secret **phrase** for the --suri parameter (**not** the secret seed)
3. Also use the secret phrase for the --suri parameter in:
 - step 4 ('Insert the grandpa secret key...')
 - in the 'Enable other participants to join' section, steps 5 & 6
4. In the 'Enable other participants to join' section, step 9 ('Restart the second blockchain node...'), observe that the node runs for a few seconds before shutting down due to a 'GRANDPA voting error'

node-template version is `node-template 4.0.0-dev-b53da9f-x86_64-linux-gnu`

**Comment by lisa-parity** [comment] 2022-02-26 18:49
Hi @liamhession , I suspect something else went wrong. I have tested using the secret phrase on macOS and Ubuntu server and it works in both cases. Maybe you had a typo or something in the seed phrase?
In any case, I'm glad you got it working, but the -`-suri <seed-phase>` option (with the phrase enclosed by quotation marks) seems to be working as expected for me.
Maybe you can capture more details to try to reproduce or close the issue?

**Comment by gslancaster** [comment] 2022-02-28 11:54
The two issues do seem connected.

If you add `--password-interactive` to the node startup command, as in issue #762, then using the secret phrase works as well as using the secret seed. With the secret seed, `--password-interactive` isn't needed though.

If you use secret phrase without passing `--password-interactive` to node startup, that still doesn't work for me. Using Ubuntu 20.04 LTS.

**Closed** 2022-03-24 18:59 UTC
Labels: bug 🐛, web-dev 🕸
