### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by HaPuLo** [substrate-developer-hub/substrate-docs#419] opened 2021-10-23 06:00 UTC
### Broken URL

https://docs.substrate.io/awesome-substrate/

### Expected redirect

https://docs.substrate.io/awesome-substrate/

**Comment by sacha-l** [comment] 2021-11-08 18:01
@HaPuLo - is this a request or a broken link you found?

**Comment by NukeManDan** [comment] 2021-11-11 00:36
duplicate of #505 - about to be closed

**Closed by NukeManDan** 2021-11-11 00:36 UTC
Labels: bug 🐛, web-dev 🕸, broken link ❌
