### ISSUE TITLE
Update loosely coupling pallets to be more clear

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#958] opened 2022-04-18 15:47 UTC
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Example is reported to be not super representative of how to design loosely coupled pallets: https://docs.substrate.io/how-to-guides/v3/pallet-design/loose-coupling/

Other resources: 
- https://substrate.recipes/pallet-coupling.html?highlight=loos#loose-coupling

cc @al3mart 

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment] 2022-07-14 22:24
Not really enough information here to be actionable, at least from the documentation point of view.
Can we get some additional context/explanation or close this issue to tidy things up in the issues queue?

**Closed** 2022-08-16 09:33 UTC
Labels: new content 💡✍️, improvement

**Comment by al3mart** [comment] 2022-08-17 08:35
I guess some color on why I closed the issue is needed.

This issue was created after I suggested Dan that maybe the content we had on loosely coupling was not very descriptive, but this week I revisited what we have in there and everything made sense to me.
I cannot recall if the content has been modified, but this time I won't change anything, I feel it shows really well what loosely coupling is about and how to achieve it.

As I say, I cannot recall if the content at the time was the same than now, as this happened before all the documentation refactoring, so maybe this suggestion came from a lack of understanding I had at the time. Only thing I can say today is that I really like how this section is and I won't change it.
