### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by shiyivei** [substrate-developer-hub/substrate-docs#1100] opened 2022-06-07 15:06 UTC
the [Substrate RPC API](https://docs.substrate.io/rustdocs/latest/sc_rpc_api/index.html) landing page is 404

**Comment by lisa-parity** [comment] 2022-06-22 20:43
@jonnysmillie, do you know where this reference is? Maybe the issue is fixed already?I'm not finding this link in the current doc:
https://docs.substrate.io/rustdocs/latest/sc_rpc_api/index.html

**Comment by lisa-parity** [comment] 2022-06-24 17:29
This link isn't in the documentation anymore and we aren't using the rustdocs path, so this is a no op. Closing.

**Closed by lisa-parity** 2022-06-24 17:29 UTC
